# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment to digital ocean ci cd pipeline method

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 142.93.159.121
        username: root
        key: ${{ secrets.key }}
        port: 22
        script: whoami
